# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Implant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implantID', models.CharField(max_length=32)),
                ('userID', models.CharField(max_length=32)),
                ('command', models.CharField(max_length=32)),
                ('macAddress', models.CharField(max_length=20)),
                ('ipAddress', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=32)),
                ('implantID', models.CharField(max_length=32)),
                ('file_type', models.CharField(max_length=16)),
                ('data', models.FileField(upload_to='files/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
